---
title: "UrchinSurveyMap"
author: "Delaney Chabot"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load packages
```{r}
library(ggplot2)
#library(ggsn)
library(maps)
library(mapdata)
library(ggrepel)
library(readxl)
library(tidyverse)
library(ggspatial)
```

**THIS IS FROM ANOTHER PROJECT AND NEEDS TO BE ADJUSTED TO THE urchin survey SITES**
Import Data
```{r}
#Map of Sites----
SiteList <- read.csv("Data/IntertidalUrchinSites.csv")

View(SiteList)


long <- SiteList$Longitude
lat <- SiteList$Latitude
Site <-SiteList$Site
Reg <-SiteList$Region
Reg<-factor(Reg, levels=c('Cape Foulweather','Cape Perpetua','Cape Arago','Cape Blanco', "Southern Oregon', 'Cape Mendocino"))#change Pred to a factor and make order for graphing and such

SiteCode <-SiteList$SiteCode
```

Make base map
```{r}
states <- map_data("state")
#states <- states %>% #include for only Oregon and California
#  subset(region %in% c("california", "oregon"))
```

Customize map need to figure out colors. 
```{r}
map <-ggplot(data = SiteList, 
             aes(x=long, y = lat, color = Region)) +   
  geom_polygon(data = states, color = "black", fill = "gray90", aes(group=group)) + 
  geom_point(aes(shape = State), size = 2) +
  scale_color_manual(values= c("#0072B2","#009E73","#D55E00", "#f94144",  "#66BBBB","#555599")) +
  labs(x = bquote("Longitude ("*degree~"W)"),
       y = bquote("Latitude ("*degree~"N)")) +
  annotate("text", color = c("#0072B2","#009E73","#D55E00",  "#f94144", "#555599", "#66BBBB"),
           size = 3.5,
           fontface = "bold",
           x = c(-122.1, -122.1, -122.7, -122.8, -122.5, -122.3),
           y = c(45, 44.6, 43.4, 43, 42.2, 40.5),
           label = c("Cape Foulweather",
                     "Cape Perpetua", "Cape Arago", "Cape Blanco",
                     "Southern Oregon", "Cape Mendocino")) +
  scale_x_continuous(breaks = seq(-128,-114,2)) +
  scale_y_continuous(breaks = seq(32,46,1)) +
  scale_shape_manual(values = c(16,1)) +
  coord_map(xlim = c(-126,-118), ylim = c(40,46)) +
  theme(legend.position = "none",
        panel.grid.major=element_blank(),
        panel.background=element_blank(),
        panel.border=element_rect(color="black",fill=NA,size=1),
        axis.text=element_text(color="black", size=10), 
        axis.ticks=element_line(color="black")) +
  geom_label_repel(mapping = aes(x= long, y= lat, label = SiteCode), 
                   label.size = NA,
                   hjust = 1, 
                   force_pull = 0,
                   #nudge_x = -0.5,
                   #nudge_y = -0.3,
                   xlim = c(-1, -0.09),
                   box.padding = 0, 
                   label.padding = 0.15,
                   size=3.5) 
  # scalebar(location = "bottomright", dist = 200, dist_unit = "km", 
  #          transform = TRUE, model = "WGS84", height = 0.02, st.dist = 0.025,
  #          st.size = 3.25, border.size = 0.5,
  #          x.min = -128, x.max = -114, 
  #          y.min = 32, y.max = 46,
  #          anchor = c(x=-121, y=32.5)) +
  #annotation_north_arrow(height = unit(1, "cm"),
                         # width = unit(0.67, "cm"),
                         # pad_x = unit(0.5, "cm"),
                         # pad_y = unit(0.5, "cm"),
                         # rotation = NULL,
                         # style = north_arrow_orienteering)

plot(map)
#ggsave("LP_Map_final.pdf", width = 4, height = 5)
#ggsave("LP_Map_final.jpg", width = 4, height = 5, dpi = 2000)
```

Old Map???
```{r}
#map it
map <-ggplot(data = SiteList, 
             aes(x=long, 
                 y = lat, color = Reg)) +   
  geom_text_repel(aes( label = SiteCode),
                  direction = "y", 
                   nudge_x = -125, 
                   min.segment.length = 0, 
                   seed = 42, 
                   box.padding = 0.5,
                  size=3)+
  geom_polygon(data = states, color = "black", fill = "white", aes(group=group)) + 
  geom_point(size = 2, shape = 16) +
  scale_color_manual(values= c("#577590","#90be6d","#f8961e", "#f94144", "#555599", "#66BBBB")) +
  coord_fixed(1.3) +
  theme_classic()+
  labs(x="Longitude", y = "Latitude") +
  scale_x_continuous(breaks = seq(-126,-116,2)) +
  scale_y_continuous(breaks = seq(31,47,1)) +
  coord_map(xlim = c(-126,-116), ylim = c(40,47))+
  theme(legend.position = "none") 
  

plot(map)
#ggsave("Map.png", width = 4, height = 6)
#ggsave("Map.eps", width = 4, height = 6)
#Don't overwrite these, I edited in illustrator
```



